version: '3.9'
services:
    webapi:
        build: .
        container_name: aspnet-app
        ports:
            - "8080:8080"
        depends_on:
            - sqlserver
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - sql_data:/var/opt/mssql

volumes:
    sql_data:
